package com.byteflair.parkplan.api.domain.type;

public enum NotificationType {
	OUT_OF_BOUNDS, TRACK_GSM_LOST, TRACK_PASSIVE_END, POSITION_REGISTERED, DEVICE_ACCESS_ACCREDITED, DEVICE_ACCESS_REVOKED, CLIENT_ACCESS_REVOKED;
}